app:
  token: ${API_KEY}
  test: false
  database:
    type: sqlite  # or sqlite
    postgres:
      host: ${DB_HOST}
      port: 5432
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      dbname: ${DB_NAME}
    sqlite:
      path: test.db
  stickers:
    positive:
      - "AgADshgAAt5nkFA"
    negative:
      - "AgADAhoAAjTMkVA"
    transfer:
      - "AgAD8RcAAgJ8kFA"
  capitalist:
    initial_balance: 20
  activity_check:
    schedule: "0 */12 * * *"  # Every 12 hours
    response_timeout: 43200  # Time in seconds to wait for response (12 hours)
    max_retries: 4  # Maximum number of retries before marking as inactive
    retry_interval: 10800  # Time in seconds between retries (3 hours)
    channels:
      alerts: ${CHANNEL_ID}  # Replace with your channel ID
      warnings: ${CHANNEL_ID} # Replace with your channel ID
    rewards:
      alive_score: 1  # Points awarded for responding to activity check
