app:
  token: ${API_KEY}
  test: false
  database:
    type: sqlite  # or sqlite
    postgres:
      host: ${DB_HOST}
      port: 5432
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      dbname: ${DB_NAME}
    sqlite:
      path: test.db
  stickers:
    positive:
      - "AgADshgAAt5nkFA"
    negative:
      - "AgADAhoAAjTMkVA"
    transfer:
      - "AgAD8RcAAgJ8kFA"
  capitalist:
    initial_balance: 20
