app:
  token: ${API_KEY}
  test: true
  database:
    type: mysql  # or sqlite
    mysql:
      host: 127.0.0.1
      port: 3306
      user: root
      password: yourPass
      dbname: social_credit
    sqlite:
      path: test.db
  stickers:
    positive:
      - "AgADshgAAt5nkFA"
    negative:
      - "AgADAhoAAjTMkVA"
    transfer:
      - "AgAD8RcAAgJ8kFA"
  capitalist:
    initial_balance: 20
